
import React, { useState, useEffect, useRef } from 'react';
import { Lead } from '../../types';
import { generateAudioPitch, SESSION_ASSETS, subscribeToAssets, generateVisual } from '../../services/geminiService';
import { kieSunoService } from '../../services/kieSunoService';
import { SonicPromptGuide } from './SonicPromptGuide';
import { SonicStudioPlayer } from './SonicStudioPlayer';

interface SonicStudioProps {
  lead?: Lead;
}

type StudioMode = 'MUSIC' | 'VOICE';

const MUSIC_GENRES = [
  { value: 'electronic', label: 'Electronic / Synth' },
  { value: 'hip_hop', label: 'Hip Hop / Trap' },
  { value: 'rock', label: 'Rock / Metal' },
  { value: 'pop', label: 'Modern Pop' },
  { value: 'jazz', label: 'Jazz / Blues' },
  { value: 'cinematic', label: 'Cinematic / Orchestral' },
  { value: 'ambient', label: 'Ambient / Lo-fi' },
  { value: 'corporate', label: 'Corporate / Upbeat' }
];

const MUSIC_VIBES = [
  { value: 'uplifting', label: 'Uplifting & Energetic' },
  { value: 'chill', label: 'Chill & Relaxed' },
  { value: 'dark', label: 'Dark & Moody' },
  { value: 'epic', label: 'Epic & Intense' },
  { value: 'romantic', label: 'Romantic & Soft' },
  { value: 'mysterious', label: 'Mysterious & Tense' },
  { value: 'tech', label: 'Futuristic & Tech' }
];

export const SonicStudio: React.FC<SonicStudioProps> = ({ lead }) => {
  const [mode, setMode] = useState<StudioMode>('MUSIC'); // Default to MUSIC
  
  // Voice State
  const defaultScript = lead 
    ? lead.personalizedHook || `Hello ${lead.businessName}, I see a huge opportunity to dominate the ${lead.city} market with AI video automation. Let's chat.`
    : "This is a sample audio pitch generated by Pomelli Sonic Studio. We automate your outreach at scale.";
  const [voiceText, setVoiceText] = useState(defaultScript);
  
  // Music State
  const [musicPrompt, setMusicPrompt] = useState(lead ? `Suitable for ${lead.niche} brand campaign.` : "Background music for video content.");
  const [selectedGenre, setSelectedGenre] = useState(MUSIC_GENRES[0]);
  const [selectedVibe, setSelectedVibe] = useState(MUSIC_VIBES[0]);
  const [isInstrumental, setIsInstrumental] = useState(true);
  
  // Cover Art State
  const [coverImage, setCoverImage] = useState<string | null>(null);
  const [isGeneratingCover, setIsGeneratingCover] = useState(false);
  const coverInputRef = useRef<HTMLInputElement>(null);

  // Common State
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedAssets, setGeneratedAssets] = useState<any[]>([]);
  const [logs, setLogs] = useState<string[]>([]);
  const [showGuide, setShowGuide] = useState(false);

  // Asset Subscription
  useEffect(() => {
    const initialAudio = SESSION_ASSETS.filter(a => a.type === 'AUDIO');
    setGeneratedAssets(initialAudio);

    const unsub = subscribeToAssets((allAssets) => {
        const audioAssets = allAssets.filter(a => a.type === 'AUDIO');
        setGeneratedAssets(audioAssets);
    });
    return () => unsub();
  }, []);

  // Sync when lead changes
  useEffect(() => {
    if (lead) {
        setVoiceText(lead.personalizedHook || `Hello ${lead.businessName}, I see a huge opportunity to dominate the ${lead.city} market with AI video automation. Let's chat.`);
        setMusicPrompt(`Suitable for ${lead.niche} brand campaign.`);
        if (lead.niche.toLowerCase().includes('tech') || lead.niche.toLowerCase().includes('saas')) {
            setSelectedGenre(MUSIC_GENRES.find(g => g.value === 'electronic') || MUSIC_GENRES[0]);
            setSelectedVibe(MUSIC_VIBES.find(v => v.value === 'tech') || MUSIC_VIBES[0]);
        }
    }
  }, [lead?.id]);

  const addLog = (msg: string) => setLogs(prev => [`[${new Date().toLocaleTimeString()}] ${msg}`, ...prev].slice(0, 10));

  const handleVoiceGenerate = async () => {
    if (!voiceText) return;
    setIsGenerating(true);
    addLog("Initializing Neural TTS Core...");
    
    try {
      const url = await generateAudioPitch(voiceText, 'Kore', lead?.id);
      if (url) {
        addLog("Voice Synthesis Complete.");
      } else {
        addLog("Error: TTS Synthesis Failed.");
      }
    } catch (e: any) {
      console.error(e);
      addLog(`Error: ${e.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleMusicGenerate = async () => {
    if (!musicPrompt) return;
    setIsGenerating(true);
    addLog("Contacting Suno Music Engine...");

    const finalPrompt = `${selectedVibe.label} ${selectedGenre.label} music, ${musicPrompt}`;
    addLog(`Prompt: ${finalPrompt.slice(0, 40)}...`);

    try {
      // Pass coverImage if available
      const urls = await kieSunoService.runFullCycle(finalPrompt, isInstrumental, lead?.id, coverImage || undefined);
      if (urls.length > 0) {
        addLog(`Success: ${urls.length} tracks generated.`);
      } else {
        addLog("Music Task Completed but no audio returned.");
      }
    } catch (e: any) {
      console.error(e);
      addLog(`Music Error: ${e.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCoverUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
        const reader = new FileReader();
        reader.onload = (ev) => {
            setCoverImage(ev.target?.result as string);
            addLog("Custom cover art uploaded.");
        };
        reader.readAsDataURL(file);
    }
  };

  const handleGenerateCover = async () => {
    setIsGeneratingCover(true);
    addLog("Generating Album Art...");
    try {
        const prompt = `Album cover art for ${selectedGenre.label} music, ${selectedVibe.label} vibe. ${musicPrompt}. High quality, 4k, digital art.`;
        const url = await generateVisual(prompt, lead);
        if (url) {
            setCoverImage(url);
            addLog("Album art generated.");
        }
    } catch (e) {
        console.error(e);
        addLog("Failed to generate cover art.");
    } finally {
        setIsGeneratingCover(false);
    }
  };

  return (
    <div className="max-w-[1600px] mx-auto py-8 space-y-12 animate-in fade-in duration-500 relative">
      
      {showGuide && (
        <SonicPromptGuide 
          onClose={() => setShowGuide(false)} 
          onSelect={(t) => {
            setMusicPrompt(t);
            setShowGuide(false);
          }} 
        />
      )}

      <div className="flex justify-between items-end border-b border-slate-800/50 pb-8">
        <div>
          <h1 className="text-4xl font-black italic text-white uppercase tracking-tighter">SONIC <span className="text-emerald-600 not-italic">STUDIO</span></h1>
          <p className="text-[10px] text-slate-400 font-black uppercase tracking-[0.4em] mt-2 italic italic">
            Audio Synthesis Lab: {lead ? lead.businessName : 'Sandbox'}
          </p>
        </div>
        <div className="flex gap-2 bg-[#0b1021] border border-slate-800 rounded-lg p-1">
           <button 
             onClick={() => setMode('MUSIC')}
             className={`px-6 py-2 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${mode === 'MUSIC' ? 'bg-emerald-600 text-white shadow-lg' : 'text-slate-500 hover:text-white'}`}
           >
             SUNO MUSIC
           </button>
           <button 
             onClick={() => setMode('VOICE')}
             className={`px-6 py-2 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${mode === 'VOICE' ? 'bg-emerald-600 text-white shadow-lg' : 'text-slate-500 hover:text-white'}`}
           >
             VOICE PITCH
           </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* LEFT CONTROL PANEL */}
        <div className="lg:col-span-4 space-y-6">
           <div className="bg-[#0b1021] border border-slate-800 rounded-[32px] p-8 shadow-2xl space-y-8">
              
              {/* VOICE CONTROLS */}
              {mode === 'VOICE' && (
                <div className="space-y-6 animate-in slide-in-from-left-4">
                   <div className="space-y-2">
                      <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest ml-1">Script</label>
                      <textarea 
                        value={voiceText}
                        onChange={(e) => setVoiceText(e.target.value)}
                        className="w-full bg-[#020617] border border-slate-800 rounded-2xl p-5 text-[11px] font-bold text-slate-300 focus:outline-none focus:border-emerald-500 h-48 resize-none shadow-xl italic"
                        placeholder="Enter speech script..."
                      />
                   </div>
                   <button 
                     onClick={handleVoiceGenerate}
                     disabled={isGenerating}
                     className="w-full bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white py-5 rounded-2xl text-[11px] font-black uppercase tracking-[0.3em] transition-all shadow-xl shadow-emerald-600/20 active:scale-95 border-b-4 border-emerald-800"
                   >
                     {isGenerating ? 'SYNTHESIZING...' : 'GENERATE SPEECH'}
                   </button>
                </div>
              )}

              {/* MUSIC CONTROLS */}
              {mode === 'MUSIC' && (
                <div className="space-y-6 animate-in slide-in-from-right-4">
                   
                   {/* ALBUM ART GENERATOR */}
                   <div className="space-y-2">
                      <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest ml-1">Cover Art (Optional)</label>
                      <div className="flex gap-4 items-center">
                          <div 
                            onClick={() => coverInputRef.current?.click()}
                            className="w-24 h-24 rounded-2xl border-2 border-dashed border-slate-700 bg-slate-900/50 flex flex-col items-center justify-center cursor-pointer hover:border-emerald-500/50 hover:bg-slate-900 transition-all overflow-hidden relative group"
                          >
                             {coverImage ? (
                               <img src={coverImage} className="w-full h-full object-cover" />
                             ) : (
                               <span className="text-2xl opacity-50 group-hover:opacity-100 group-hover:scale-110 transition-all">🖼️</span>
                             )}
                             {isGeneratingCover && (
                               <div className="absolute inset-0 bg-black/60 flex items-center justify-center">
                                  <div className="w-6 h-6 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                               </div>
                             )}
                             <input type="file" ref={coverInputRef} onChange={handleCoverUpload} className="hidden" accept="image/*" />
                          </div>
                          <div className="flex-1 flex flex-col gap-2">
                             <button 
                               onClick={handleGenerateCover}
                               disabled={isGeneratingCover}
                               className="w-full py-3 bg-slate-900 border border-slate-700 hover:border-emerald-500 text-slate-300 hover:text-white rounded-xl text-[9px] font-black uppercase tracking-widest transition-all"
                             >
                               {isGeneratingCover ? 'GENERATING...' : '✨ GENERATE AI COVER'}
                             </button>
                             <button 
                               onClick={() => coverInputRef.current?.click()}
                               className="w-full py-3 bg-slate-900 border border-slate-700 hover:border-slate-500 text-slate-400 hover:text-white rounded-xl text-[9px] font-black uppercase tracking-widest transition-all"
                             >
                               ⬆️ UPLOAD IMAGE
                             </button>
                          </div>
                      </div>
                   </div>

                   <hr className="border-slate-800" />

                   {/* GENRE & VIBE SELECTORS */}
                   <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                         <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest ml-1">Genre</label>
                         <select 
                           value={selectedGenre.value}
                           onChange={(e) => setSelectedGenre(MUSIC_GENRES.find(g => g.value === e.target.value) || MUSIC_GENRES[0])}
                           className="w-full bg-[#020617] border border-slate-800 rounded-xl px-3 py-3 text-[10px] font-bold text-slate-300 focus:outline-none focus:border-emerald-500 uppercase tracking-widest cursor-pointer"
                         >
                            {MUSIC_GENRES.map(g => <option key={g.value} value={g.value}>{g.label}</option>)}
                         </select>
                      </div>
                      <div className="space-y-2">
                         <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest ml-1">Vibe</label>
                         <select 
                           value={selectedVibe.value}
                           onChange={(e) => setSelectedVibe(MUSIC_VIBES.find(v => v.value === e.target.value) || MUSIC_VIBES[0])}
                           className="w-full bg-[#020617] border border-slate-800 rounded-xl px-3 py-3 text-[10px] font-bold text-slate-300 focus:outline-none focus:border-emerald-500 uppercase tracking-widest cursor-pointer"
                         >
                            {MUSIC_VIBES.map(v => <option key={v.value} value={v.value}>{v.label}</option>)}
                         </select>
                      </div>
                   </div>

                   <div className="space-y-2">
                      <div className="flex justify-between items-center">
                        <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest ml-1">Prompt Context</label>
                        <button onClick={() => setShowGuide(true)} className="text-[9px] font-black text-emerald-400 hover:text-white uppercase tracking-widest transition-colors flex items-center gap-1">
                           <span>ⓘ</span> GUIDE
                        </button>
                      </div>
                      <textarea 
                        value={musicPrompt}
                        onChange={(e) => setMusicPrompt(e.target.value)}
                        className="w-full bg-[#020617] border border-slate-800 rounded-2xl p-5 text-[11px] font-bold text-slate-300 focus:outline-none focus:border-emerald-500 h-24 resize-none shadow-xl italic"
                        placeholder="Additional details (instruments, tempo, use case)..."
                      />
                   </div>
                   
                   <div className="flex items-center gap-3 bg-slate-900 p-4 rounded-xl border border-slate-800">
                      <input 
                        type="checkbox" 
                        checked={isInstrumental} 
                        onChange={(e) => setIsInstrumental(e.target.checked)}
                        className="w-4 h-4 accent-emerald-500"
                      />
                      <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">INSTRUMENTAL ONLY</span>
                   </div>

                   <button 
                     onClick={handleMusicGenerate}
                     disabled={isGenerating}
                     className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white py-5 rounded-2xl text-[11px] font-black uppercase tracking-[0.3em] transition-all shadow-xl shadow-indigo-600/20 active:scale-95 border-b-4 border-indigo-800"
                   >
                     {isGenerating ? 'COMPOSING...' : 'GENERATE MUSIC (SUNO)'}
                   </button>
                </div>
              )}

              {/* LOGS */}
              <div className="bg-slate-950 border border-slate-800 rounded-2xl p-4 h-32 overflow-y-auto custom-scrollbar font-mono text-[9px] space-y-2 shadow-inner">
                 {logs.map((l, i) => (
                    <div key={i} className="text-emerald-500/80 border-b border-slate-800/50 pb-1 last:border-0">{l}</div>
                 ))}
                 {logs.length === 0 && <span className="text-slate-600 italic">SYSTEM READY</span>}
              </div>
           </div>
        </div>

        {/* RIGHT: OUTPUT AREA */}
        <div className="lg:col-span-8 h-full min-h-[600px] relative">
           <SonicStudioPlayer assets={generatedAssets} />
           
           {/* LOADING OVERLAY */}
           {isGenerating && (
              <div className="absolute inset-0 bg-slate-950/80 backdrop-blur-sm z-50 flex flex-col items-center justify-center space-y-6 rounded-[32px]">
                 <div className="w-16 h-16 border-4 border-emerald-500/20 border-t-emerald-500 rounded-full animate-spin"></div>
                 <p className="text-[10px] font-black text-emerald-400 uppercase tracking-[0.3em] animate-pulse">PROCESSING AUDIO WAVEFORMS...</p>
              </div>
           )}
        </div>
      </div>
    </div>
  );
};
