
import React, { useState, useEffect, useRef } from 'react';
import { Lead } from '../../types';
import { generateAudioPitch } from '../../services/geminiService';
import { kieSunoService } from '../../services/kieSunoService';

interface SonicStudioProps {
  lead?: Lead;
}

type StudioMode = 'VOICE' | 'MUSIC';

export const SonicStudio: React.FC<SonicStudioProps> = ({ lead }) => {
  const [mode, setMode] = useState<StudioMode>('VOICE');
  
  // Voice State
  const defaultScript = lead 
    ? lead.personalizedHook || `Hello ${lead.businessName}, I see a huge opportunity to dominate the ${lead.city} market with AI video automation. Let's chat.`
    : "This is a sample audio pitch generated by Pomelli Sonic Studio. We automate your outreach at scale.";
  const [voiceText, setVoiceText] = useState(defaultScript);
  
  // Music State
  const defaultMusicPrompt = lead
    ? `Upbeat corporate electronic background music, inspiring, tech-forward, suitable for ${lead.niche} brand.`
    : "Lo-fi chill hip hop beats, relaxing, study music";
  const [musicPrompt, setMusicPrompt] = useState(defaultMusicPrompt);
  const [isInstrumental, setIsInstrumental] = useState(true);

  // Common State
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedAssets, setGeneratedAssets] = useState<{ type: 'VOICE' | 'MUSIC', url: string, label: string }[]>([]);
  const [logs, setLogs] = useState<string[]>([]);

  // Sync when lead changes
  useEffect(() => {
    if (lead) {
        setVoiceText(lead.personalizedHook || `Hello ${lead.businessName}, I see a huge opportunity to dominate the ${lead.city} market with AI video automation. Let's chat.`);
        setMusicPrompt(`Upbeat corporate electronic background music, inspiring, tech-forward, suitable for ${lead.niche} brand.`);
    }
  }, [lead?.id]);

  const addLog = (msg: string) => setLogs(prev => [`[${new Date().toLocaleTimeString()}] ${msg}`, ...prev].slice(0, 5));

  const handleVoiceGenerate = async () => {
    if (!voiceText) return;
    setIsGenerating(true);
    addLog("Initializing Neural TTS Core...");
    
    try {
      const url = await generateAudioPitch(voiceText, 'Kore', lead?.id);
      if (url) {
        setGeneratedAssets(prev => [{ type: 'VOICE', url, label: 'Sales Pitch (Kore)' }, ...prev]); 
        addLog("Voice Synthesis Complete.");
      } else {
        addLog("Error: TTS Synthesis Failed.");
      }
    } catch (e: any) {
      console.error(e);
      addLog(`Error: ${e.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleMusicGenerate = async () => {
    if (!musicPrompt) return;
    setIsGenerating(true);
    addLog("Contacting Suno Music Engine...");

    try {
      const urls = await kieSunoService.runFullCycle(musicPrompt, isInstrumental, lead?.id);
      if (urls.length > 0) {
        const newAssets = urls.map((u, i) => ({ 
            type: 'MUSIC' as const, 
            url: u, 
            label: `Generated Track ${i+1}: ${musicPrompt.slice(0, 15)}...` 
        }));
        setGeneratedAssets(prev => [...newAssets, ...prev]);
        addLog("Music Generation Successful.");
      } else {
        addLog("Music Task Completed but no audio returned.");
      }
    } catch (e: any) {
      console.error(e);
      addLog(`Music Error: ${e.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto py-8 space-y-12 animate-in fade-in duration-500">
      <div className="flex justify-between items-end border-b border-slate-800/50 pb-8">
        <div>
          <h1 className="text-4xl font-black italic text-white uppercase tracking-tighter">SONIC <span className="text-emerald-600 not-italic">STUDIO</span></h1>
          <p className="text-[10px] text-slate-400 font-black uppercase tracking-[0.4em] mt-2 italic italic">
            Audio Synthesis Lab: {lead ? lead.businessName : 'Sandbox'}
          </p>
        </div>
        <div className="flex gap-2 bg-[#0b1021] border border-slate-800 rounded-lg p-1">
           <button 
             onClick={() => setMode('VOICE')}
             className={`px-6 py-2 rounded text-[10px] font-black uppercase tracking-widest transition-all ${mode === 'VOICE' ? 'bg-emerald-600 text-white' : 'text-slate-500 hover:text-white'}`}
           >
             VOICE PITCH
           </button>
           <button 
             onClick={() => setMode('MUSIC')}
             className={`px-6 py-2 rounded text-[10px] font-black uppercase tracking-widest transition-all ${mode === 'MUSIC' ? 'bg-emerald-600 text-white' : 'text-slate-500 hover:text-white'}`}
           >
             SUNO MUSIC
           </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div className="lg:col-span-4 space-y-6">
           <div className="bg-[#0b1021] border border-slate-800 rounded-[32px] p-10 shadow-2xl space-y-8">
              
              {/* VOICE CONTROLS */}
              {mode === 'VOICE' && (
                <div className="space-y-6 animate-in slide-in-from-left-4">
                   <div className="space-y-2">
                      <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest ml-1">Script</label>
                      <textarea 
                        value={voiceText}
                        onChange={(e) => setVoiceText(e.target.value)}
                        className="w-full bg-[#020617] border border-slate-800 rounded-2xl p-5 text-[11px] font-bold text-slate-300 focus:outline-none focus:border-emerald-500 h-48 resize-none shadow-xl italic"
                        placeholder="Enter speech script..."
                      />
                   </div>
                   <button 
                     onClick={handleVoiceGenerate}
                     disabled={isGenerating}
                     className="w-full bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white py-5 rounded-2xl text-[11px] font-black uppercase tracking-[0.3em] transition-all shadow-xl shadow-emerald-600/20 active:scale-95 border-b-4 border-emerald-800"
                   >
                     {isGenerating ? 'SYNTHESIZING...' : 'GENERATE SPEECH'}
                   </button>
                </div>
              )}

              {/* MUSIC CONTROLS */}
              {mode === 'MUSIC' && (
                <div className="space-y-6 animate-in slide-in-from-right-4">
                   <div className="space-y-2">
                      <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest ml-1">Musical Vibe</label>
                      <textarea 
                        value={musicPrompt}
                        onChange={(e) => setMusicPrompt(e.target.value)}
                        className="w-full bg-[#020617] border border-slate-800 rounded-2xl p-5 text-[11px] font-bold text-slate-300 focus:outline-none focus:border-emerald-500 h-32 resize-none shadow-xl italic"
                        placeholder="Describe the music style, mood, and instruments..."
                      />
                   </div>
                   
                   <div className="flex items-center gap-3 bg-slate-900 p-4 rounded-xl border border-slate-800">
                      <input 
                        type="checkbox" 
                        checked={isInstrumental} 
                        onChange={(e) => setIsInstrumental(e.target.checked)}
                        className="w-4 h-4 accent-emerald-500"
                      />
                      <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">INSTRUMENTAL ONLY</span>
                   </div>

                   <button 
                     onClick={handleMusicGenerate}
                     disabled={isGenerating}
                     className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white py-5 rounded-2xl text-[11px] font-black uppercase tracking-[0.3em] transition-all shadow-xl shadow-indigo-600/20 active:scale-95 border-b-4 border-indigo-800"
                   >
                     {isGenerating ? 'COMPOSING...' : 'GENERATE MUSIC (SUNO)'}
                   </button>
                </div>
              )}

              {/* LOGS */}
              <div className="bg-slate-950 border border-slate-800 rounded-2xl p-4 h-32 overflow-y-auto custom-scrollbar font-mono text-[9px] space-y-2 shadow-inner">
                 {logs.map((l, i) => (
                    <div key={i} className="text-emerald-500/80 border-b border-slate-800/50 pb-1 last:border-0">{l}</div>
                 ))}
                 {logs.length === 0 && <span className="text-slate-600 italic">SYSTEM READY</span>}
              </div>
           </div>
        </div>

        {/* OUTPUT AREA */}
        <div className="lg:col-span-8 bg-[#0b1021] border border-slate-800 rounded-[48px] p-10 min-h-[500px] flex flex-col shadow-2xl relative overflow-hidden">
           <div className="flex-1 overflow-y-auto space-y-6 custom-scrollbar pr-4 relative z-10">
              {generatedAssets.length === 0 && !isGenerating && (
                <div className="h-full flex flex-col items-center justify-center opacity-20 italic space-y-4">
                   <span className="text-6xl grayscale">🎧</span>
                   <p className="text-[10px] font-black text-slate-600 uppercase tracking-[0.4em]">Audio Matrix Offline</p>
                </div>
              )}

              {generatedAssets.map((asset, i) => (
                <div key={i} className="bg-slate-900 border border-slate-800 p-6 rounded-[32px] hover:border-emerald-500/30 transition-all group flex flex-col gap-4 animate-in slide-in-from-bottom-2">
                   <div className="flex justify-between items-center">
                      <div className="flex items-center gap-3">
                         <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-black ${asset.type === 'MUSIC' ? 'bg-indigo-500 text-white' : 'bg-emerald-500 text-white'}`}>
                            {asset.type === 'MUSIC' ? '♫' : '🎙️'}
                         </div>
                         <h4 className="text-[11px] font-black text-white uppercase tracking-widest truncate max-w-[200px]">{asset.label}</h4>
                      </div>
                      <a href={asset.url} download={`ASSET_${i}.mp3`} className="text-[9px] font-black text-slate-500 hover:text-white uppercase tracking-widest transition-colors">DOWNLOAD</a>
                   </div>
                   
                   <div className="bg-black/40 rounded-xl p-2 border border-slate-800">
                      <audio src={asset.url} controls className="w-full h-8 opacity-80 hover:opacity-100 transition-opacity" />
                   </div>
                </div>
              ))}
           </div>
           
           {isGenerating && (
              <div className="absolute inset-0 bg-slate-950/80 backdrop-blur-sm z-20 flex flex-col items-center justify-center space-y-6">
                 <div className="w-16 h-16 border-4 border-emerald-500/20 border-t-emerald-500 rounded-full animate-spin"></div>
                 <p className="text-[10px] font-black text-emerald-400 uppercase tracking-[0.3em] animate-pulse">PROCESSING AUDIO WAVEFORMS...</p>
              </div>
           )}
        </div>
      </div>
    </div>
  );
};
